[project]
name = "proj-dtsearch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "gradio>=6.3.0",
    "ipykernel>=7.1.0",
    "openai>=2.15.0",
    "pytest>=9.0.2",
]
